#!/bin/sh

export REPOSITORY_ROOT=$HOME/repositories
export DOTFILES_ROOT=$REPOSITORY_ROOT/self/dotfiles

. $DOTFILES_ROOT/bin/folder-autoload $DOTFILES_ROOT/sh.d

if [ "$0" = "bash" ]; then
	. $DOTFILES_ROOT/bin/folder-autoload $DOTFILES_ROOT/bash.d
fi

