#!/bin/sh

export REPOSITORY_ROOT=$HOME/repositories
export DOTFILES_HOME=$REPOSITORY_ROOT/self/dotfiles

. $DOTFILES_HOME/bin/folder-autoload $DOTFILES_HOME/sh.d
. $DOTFILES_HOME/bin/folder-autoload $DOTFILES_HOME/x.d

if [ "$0" = "bash" ]; then
  #bashrc
  . $DOTFILES_HOME/bin/folder-autoload $DOTFILES_HOME/bash.d
elif [ "$0" = "-bash" ]; then
  #bash_profile/login
  startx
fi

