#!/bin/sh

REPOSITORY_ROOT=$HOME/repositories
DOTFILES_ROOT=$REPOSITORY_ROOT/self/dotfiles

$DOTFILES_ROOT/bin/folder-autoload $DOTFILES_ROOT/shell.d

if [ "$0" = "bash" ]; then
	$DOTFILES_ROOT/bin/folder-autoload $DOTFILES_ROOT/bash.d
fi

