#!/bin/sh

for file in ~/.dotfiles/**/[0-9][0-9]_*.autoload.sh; do
  echo "autoloading $file"
  . $file
done

for file in ~/.dotfiles/**/[0-9][0-9]_*.autoload.bash; do
  echo "autoloading $file"
  . $file
done
