#!/bin/bash
echo "loading ~/dotfiles/load_bash"

. ~/dotfiles/shell/rbenv
. ~/dotfiles/shell/node
. ~/dotfiles/shell/kerl
. ~/dotfiles/shell/exports
. ~/dotfiles/shell/short_env

. ~/dotfiles/bash/alias
. ~/dotfiles/bash/autocomplete
. ~/dotfiles/bash/history
. ~/dotfiles/bash/prompt
. ~/dotfiles/bash/title

