#!/bin/sh

####
#load xinit common files
if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for f in /etc/X11/xinit/xinitrc.d/*; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

####
#update x resources db
xrdb -merge ~/.Xresources

####
#mouse pointer
xsetroot -cursor_name left_ptr

####
#keymap
setxkbmap -model abnt2 -layout br -variant abnt2

####
#disable pc speaker beep
xset -b

if [ "$1" == "e16" ]; then
	exec e16
elif [ "$1" == "xfce"]; then
	exec xfce4-session
else
	exec xmonad
fi

