#!/bin/sh

####
#load xinit common files
. folder-autoload /etc/X11/xinit/xinitrc.d

####
#update xresources db
cat $REPOSITORY_ROOT/solarized/solarized/xresources-colors-solarized/Xresources \
    $DOTFILES_ROOT/Xresources.d/* \
| xrdb -merge

####
#mouse pointer
xsetroot -cursor_name left_ptr &

####
#wallpaper
hsetroot -fill /usr/share/archlinux/wallpaper/archlinux-simplyblack.png

####
#keymap
setxkbmap -model abnt2 -layout br -variant abnt2 &

####
#disable pc speaker beep
xset -b &

exec xmonad

