#!/bin/sh

MISE_MINIMUM_RELEASE_AGE="7d"
export MISE_MINIMUM_RELEASE_AGE

NPM_CONFIG_BEFORE="$(date -u -d '7 days ago' '+%Y-%m-%dT%H:%M:%SZ')"
NPM_CONFIG_FROZEN_LOCKFILE="true"
NPM_CONFIG_FUND="false"
NPM_CONFIG_IGNORE_SCRIPTS="true"
npm_config_min_release_age="7"
NPM_CONFIG_MIN_RELEASE_AGE="7"
export NPM_CONFIG_BEFORE NPM_CONFIG_FROZEN_LOCKFILE NPM_CONFIG_FUND NPM_CONFIG_IGNORE_SCRIPTS npm_config_min_release_age NPM_CONFIG_MIN_RELEASE_AGE

PIP_DISABLE_PIP_VERSION_CHECK=1
PIP_UPLOADED_PRIOR_TO="$(date -u -d '7 days ago' '+%Y-%m-%dT%H:%M:%SZ')"
UV_EXCLUDE_NEWER="7 days"
export PIP_DISABLE_PIP_VERSION_CHECK PIP_UPLOADED_PRIOR_TO UV_EXCLUDE_NEWER

NPM_CONFIG_MINIMUM_RELEASE_AGE="10080"
pnpm_config_minimum_release_age="10080"
PNPM_CONFIG_MINIMUM_RELEASE_AGE="10080"
export NPM_CONFIG_MINIMUM_RELEASE_AGE pnpm_config_minimum_release_age PNPM_CONFIG_MINIMUM_RELEASE_AGE

UV_INIT_BARE="1"
VIRTUAL_ENV_DISABLE_PROMPT=1
export UV_INIT_BARE VIRTUAL_ENV_DISABLE_PROMPT
