#!/bin/sh

MISE_MINIMUM_RELEASE_AGE="3d"
export MISE_MINIMUM_RELEASE_AGE

#NPM_CONFIG_BEFORE="$(date -u -d '7 days ago' '+%Y-%m-%dT%H:%M:%SZ')"
#NPM_CONFIG_FROZEN_LOCKFILE="true"
NPM_CONFIG_FUND="false"
NPM_CONFIG_IGNORE_SCRIPTS="true"
npm_config_min_release_age="3"
#NPM_CONFIG_MIN_RELEASE_AGE="3"
export NPM_CONFIG_FUND NPM_CONFIG_IGNORE_SCRIPTS npm_config_min_release_age

PIP_DISABLE_PIP_VERSION_CHECK=1
PIP_REQUIRE_VIRTUALENV=true
UV_EXCLUDE_NEWER="3 days"
export PIP_DISABLE_PIP_VERSION_CHECK PIP_REQUIRE_VIRTUALENV UV_EXCLUDE_NEWER

#NPM_CONFIG_MINIMUM_RELEASE_AGE="4320"
pnpm_config_minimum_release_age="4320"
#PNPM_CONFIG_MINIMUM_RELEASE_AGE="4320"
export pnpm_config_minimum_release_age

UV_INIT_BARE="1"
export UV_INIT_BARE
