#!/bin/sh

export DE="xmonad"
export DESKTOP_SESSION="xmonad"

####
#load xinit common files
. folder-autoload /etc/X11/xinit/xinitrc.d

####
#keymap
setxkbmap -model abnt2 -layout br -variant abnt2 &

numlockx &

####
#xmodmap
if [ -f $HOME/.Xmodmap ]; then
  xmodmap $HOME/.Xmodmap
fi

####
#update xresources db
cat $REPOSITORY_ROOT/solarized/xresources/solarized \
    $DOTFILES_ROOT/Xresources.d/* \
| xrdb -merge

####
#mouse pointer
#xsetroot -cursor_name left_ptr &
unclutter &

####
#wallpaper
#hsetroot -fill /usr/share/archlinux/wallpaper/archlinux-simplyblack.png

####
#disable pc speaker beep
xset -b &

####
#set DPI to "redmond" 96
xrandr --dpi 96

exec xmonad

