#!/bin/sh

X_WINDOW_MANAGER=`cat "$HOME/.x_window_manager"`

case $X_WINDOW_MANAGER in
    xmonad)   exec xmonad-session
              ;;
    cinnamon) exec gnome-session-cinnamon
              ;;
    gnome)    exec gnome-session
              ;;
    *)        echo "Unknown window manager in ~/.x_window_manager."
              exit 1
              ;;
esac
