#!/usr/bin/env ruby

#list gem commands
`gem help commands`.split("\n").select { |x| x[/^    /] }.map { |x| x[0..20].strip }.delete_if { |x| x.empty? }

#from edjames (Ed James)
class BashCompletion

  def initialize(command)
    @command = command
  end

  def matches
    projects.select do |task|
      task[0, typed.length] == typed
    end
  end

  def typed
    @command[/\s(.+?)$/, 1] || ''
  end

  def projects
    %x[ls ~/Development].split
  end
end

puts BashCompletion.new(ENV["COMP_LINE"]).matches
