#!/bin/bash
echo "loading ~/dotfiles/bash/history"
# limitless .bash_history
unset HISTFILESIZE

# maximum in-memory history lines
export HISTSIZE=10000

# writes history after every command
#export PROMPT_COMMAND="history -a"

# Make some commands not show up in history
export HISTCONTROL=ignoredups
export HISTIGNORE="ls:ls *:cd:cd -:pwd;exit:date:reset:.."

shopt -s histappend
