#!/bin/bash
echo "loading ~/dotfiles/bash/prompt"

# Solarized Prompt
# inspired by:
# Sexy Bash Prompt, inspired by "Extravagant Zsh Prompt"
# A big thanks to \amethyst on Freenode

eval `dircolors -b ~/dotfiles/submodules/solarized/dircolors-solarized/dircolors.ansi-dark`

# solarized color theme
RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
YELLOW=$(tput setaf 3)
BLUE=$(tput setaf 4)
MAGENTA=$(tput setaf 5)
CYAN=$(tput setaf 6)
WHITE=$(tput setaf 7)

BOLD=$(tput bold)
RESET=$(tput sgr0)

. ~/dotfiles/shell/short_env

GIT_PS1_SHOWDIRTYSTATE=1
# to show * if there are unstaged changes and + if staged and uncommitted changes. 
GIT_PS1_SHOWSTASHSTATE=1
# to show $ if there are stashed changes. 
GIT_PS1_SHOWUNTRACKEDFILES=1
# to show % if there are untracked files. 
GIT_PS1_SHOWUPSTREAM=1
# to show < if there are unpulled changes, > if there are unpushed changes, <> if there are both, or = if everything’s synced.

export PS1="\$(history -a)\[$RESET\]\[$CYAN\]\$S_HORTPS_1 \[$MAGENTA\]\w\[$RED\]\$(__git_ps1 2> /dev/null)\n\[$WHITE\]\$ \[$RESET\]"
