#!/bin/bash
echo "loading ~/dotfiles/bash/title"

#settitle() { printf '\e]2;%s\a' "$*"; }

#XTERMTITLE="${debian_chroot:+($debian_chroot)}\u@\h: \w"

# If this is an xterm set the title to user@host:dir
case "$TERM" in
  xterm*|rxvt*)
    PS1="\[\e]0;\$BASH_COMMAND\a\]$PS1"
    ;;
  *)
    ;;
esac
